language: python

python:
- 3.6

cache: pip

install:
  - pip install -e .[dev]

script:
  - pytest --cov=earthpy
  # Build documentation
  - pushd docs && make html && popd

after_success:
  - codecov
