name: earthpy-testing
channels:
  - conda-forge
dependencies:
  # Core scientific python
  - codecov
  - numpy
  - matplotlib
  - python=3.6
  - pyqt
  - pytest
  - pytest-cov
  - seaborn

  # Geo stuff
  - rasterstats
  - geopy
  - cartopy
  - geopandas
  - rasterio
  - pysal
  - pyproj
  - scikit-image
  - gdal
  - geocoder

  # Jupyter Environment
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nb_conda
  - jupyterlab

  - pip:
      # Utilities
      - download
      - mne
      - sklearn
      - tqdm
